---
apiVersion: v1
kind: Service
metadata:
  name: react-backend-service
spec:
  type: LoadBalancer
  selector:
    app: react-backend-app
  ports:
    - port: 4000
      targetPort: 4000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-backend-deployment
  labels:
    app: react-backend-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: react-backend-app
  template:
    metadata:
      labels:
        app: react-backend-app
    spec:
      containers:
        - name: react-backend-app
          image: us-central1-docker.pkg.dev/GOOGLE_PROJECT/REPO_NAME/react-backend-img:IMAGE_SHA_TAG
