---
apiVersion: v1
kind: Service
metadata:
  name: react-frontend-service
spec:
  type: LoadBalancer
  selector:
    app: react-frontend-app
  ports:
    - port: 3000
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-frontend-deployment
  labels:
    app: react-frontend-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react-frontend-app
  template:
    metadata:
      labels:
        app: react-frontend-app
    spec:
      containers:
        - name: react-frontend-app
          image: us-central1-docker.pkg.dev/GOOGLE_PROJECT/REPO_NAME/react-frontend-img:IMAGE_SHA_TAG
