export const sample_items = [
  {
    itemId: '001',
    name:"Rural Pastoral Scene: Vintage Artwork Featuring Sheep Grazing in a Countryside Meadow, Rustic Landscape Painting, Vintage Sheep Illustration, Meadow Serenity Print",
    price: 0.1,
    freeDownload: true,
    stars: 3,
    thumbnailUrl: "0001.jpg",
    imageFolder: "0001",
    imageList: ["001-1.jpg","001-2.jpg","001-3.jpg"],
    sizeOptions: ["5x7 inches","8x8 inches","9x12 inches"],
    tags: ['Beautiful', 'Feel Good'],
  },
  {
    itemId: '002',
    name:"Wildflower Trio: Set of 3 Framed Botanical Prints on Canvas, Minimalist Floral Illustrations in Neutral Tones, Contemporary Farmhouse Wall Art, Modern Botanical ",
    price: 0.12,
    freeDownload: true,
    stars: 4,
    thumbnailUrl: "0002.jpg",
    imageFolder: "0002",
    imageList: ["002-1.jpg","002-2.jpg","002-3.jpg"],
    sizeOptions: ["5x7 inches","8x8 inches","9x12 inches"],
    tags: ['Beautiful', 'Feel Good'],
  },
  {
    itemId: '003',
    name:"Antique Countryside Vista Collection: Mega Bundle of Vintage Printable Oil Painting Reproductions, Timeless Farmhouse Landscape Depictions, Rustic Mountain Scenes for Wall Art.",
    price: 1,
    freeDownload: true,
    stars: 5,
    thumbnailUrl: "0003.jpg",
    imageFolder: "0003",
    imageList: ["003-1.jpg","003-2.jpg","003-3.jpg"],
    sizeOptions: ["5x7 inches","8x8 inches","9x12 inches"],
    tags: ['Beautiful', 'Feel Good'],
  },
  {
    itemId: '004',
    name:"Rural Pastoral Scene: Vintage Artwork Featuring Sheep Grazing in a Countryside Meadow, Rustic Landscape Painting, Vintage Sheep Illustration, Meadow Serenity Print",
    price: 0.1,
    freeDownload: true,
    stars: 3,
    thumbnailUrl: "0004.jpg",
    imageFolder: "0004",
    imageList: ["001-1.jpg","001-2.jpg","001-3.jpg"],
    sizeOptions: ["5x7 inches","8x8 inches","9x12 inches"],
    tags: ['Beautiful', 'Feel Good'],
  },
  {
    itemId: '005',
    name:"Wildflower Trio: Set of 3 Framed Botanical Prints on Canvas, Minimalist Floral Illustrations in Neutral Tones, Contemporary Farmhouse Wall Art, Modern Botanical ",
    price: 0.12,
    freeDownload: true,
    stars: 4,
    thumbnailUrl: "0005.jpg",
    imageFolder: "0005",
    imageList: ["002-1.jpg","002-2.jpg","002-3.jpg"],
    sizeOptions: ["5x7 inches","8x8 inches","9x12 inches"],
    tags: ['Beautiful', 'Feel Good'],
  },
  {
    itemId: '006',
    name:"Antique Countryside Vista Collection: Mega Bundle of Vintage Printable Oil Painting Reproductions, Timeless Farmhouse Landscape Depictions, Rustic Mountain Scenes for Wall Art.",
    price: 1,
    freeDownload: true,
    stars: 5,
    thumbnailUrl: "0006.jpg",
    imageFolder: "0006",
    imageList: ["003-1.jpg","003-2.jpg","003-3.jpg"],
    sizeOptions: ["5x7 inches","8x8 inches","9x12 inches"],
    tags: ['Beautiful', 'Feel Good'],
  },
  {
    itemId: '007',
    name:"Rural Pastoral Scene: Vintage Artwork Featuring Sheep Grazing in a Countryside Meadow, Rustic Landscape Painting, Vintage Sheep Illustration, Meadow Serenity Print",
    price: 0.1,
    freeDownload: false,
    stars: 3,
    thumbnailUrl: "0007.jpg",
    imageFolder: "0007",
    imageList: ["001-1.jpg","001-2.jpg","001-3.jpg"],
    sizeOptions: ["5x7 inches","8x8 inches","9x12 inches"],
    tags: ['Beautiful', 'Feel Good'],
  },
  {
    itemId: '008',
    name:"Wildflower Trio: Set of 3 Framed Botanical Prints on Canvas, Minimalist Floral Illustrations in Neutral Tones, Contemporary Farmhouse Wall Art, Modern Botanical ",
    price: 0.12,
    freeDownload: false,
    stars: 4,
    thumbnailUrl: "0008.jpg",
    imageFolder: "0008",
    imageList: ["002-1.jpg","002-2.jpg","002-3.jpg"],
    sizeOptions: ["5x7 inches","8x8 inches","9x12 inches"],
    tags: ['Beautiful', 'Feel Good'],
  },
  {
    itemId: '009',
    name:"Antique Countryside Vista Collection: Mega Bundle of Vintage Printable Oil Painting Reproductions, Timeless Farmhouse Landscape Depictions, Rustic Mountain Scenes for Wall Art.",
    price: 1,
    freeDownload: false,
    stars: 5,
    thumbnailUrl: "0009.jpg",
    imageFolder: "0009",
    imageList: ["003-1.jpg","003-2.jpg","003-3.jpg"],
    sizeOptions: ["5x7 inches","8x8 inches","9x12 inches"],
    tags: ['Beautiful', 'Feel Good'],
  }
]