export const sample_items = [
  {
    itemId: '001',
    name:"Rural Pastoral Scene: Vintage Artwork Featuring Sheep Grazing in a Countryside Meadow, Rustic Landscape Painting, Vintage Sheep Illustration, Meadow Serenity Print",
    price: 1,
    stars: 3,
    thumbnailUrl: "001.jpg",
    imageFolder: "001",
    imageList: ["001-1.jpg","001-2.jpg","001-3.jpg"],
    sizeOptions: ["5x7 inches","8x8 inches","9x12 inches"],
    tags: ['Beautiful', 'Feel Good'],
  },
  {
    itemId: '002',
    name:"Wildflower Trio: Set of 3 Framed Botanical Prints on Canvas, Minimalist Floral Illustrations in Neutral Tones, Contemporary Farmhouse Wall Art, Modern Botanical ",
    price: 2,
    stars: 4,
    thumbnailUrl: "002.jpg",
    imageFolder: "002",
    imageList: ["002-1.jpg","002-2.jpg","002-3.jpg"],
    sizeOptions: ["5x7 inches","8x8 inches","9x12 inches"],
    tags: ['Beautiful', 'Feel Good'],
  },
  {
    itemId: '003',
    name:"Antique Countryside Vista Collection: Mega Bundle of Vintage Printable Oil Painting Reproductions, Timeless Farmhouse Landscape Depictions, Rustic Mountain Scenes for Wall Art.",
    price: 1,
    stars: 5,
    thumbnailUrl: "003.jpg",
    imageFolder: "003",
    imageList: ["003-1.jpg","003-2.jpg","003-3.jpg"],
    sizeOptions: ["5x7 inches","8x8 inches","9x12 inches"],
    tags: ['Beautiful', 'Feel Good'],
  }
]