name: Deploy frontend

on:
  push:
    branches:
      - "main"
    paths:
      - frontend/**
      - .github/workflows/frontend-build-and-deploy.yaml
      - frontend-resources.yaml

env:
  SERVICE: online-store-frontend-cloud-run-service
  REGION: us-central1
  TAG: ${{ github.sha }}
  REPO: online-store

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: check current test_path-1
        run: echo "$PWD" && echo "test_path-1"
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: check current test_path-2
        run: echo "$PWD" && echo "test_path-2"

      - name: npm ci
        working-directory: ./frontend
        run: npm ci # or yarn install
      - name: check current test_path-3
        run: echo "$PWD" && echo "test_path-3"

      - uses: sibiraj-s/action-eslint@v3
        with:
          working-dir: ./frontend
          token: ${{ secrets.GITHUB_TOKEN }} # optional
          eslint-args: '--ignore-path=.gitignore --quiet'
          extensions: 'js,jsx,ts,tsx'
          annotations: true
      - name: check current test_path-4
        run: echo "$PWD" && echo "test_path-4"

  deploy:
    runs-on: ubuntu-latest
    needs: eslint
    steps:
      - name: Deploy production to render.com
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.RENDER_DEPLOY_HOOK_SERVICE_ID }} # Can be found as part of the Deploy Hook
          api-key: ${{ secrets.RENDER_API_KEY }} # Create your API key in Render Dashboard > Account Settings

      - name: code checkout
        uses: actions/checkout@v3

      - name: check current test_path-5
        run: echo "$PWD" && echo "test_path-5"

      - name: install the gcloud cli
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ secrets.GOOGLE_PROJECT }}
          service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          install_components: "gke-gcloud-auth-plugin"
          export_default_credentials: true

      - name: build and push the docker image
        env:
          GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
        working-directory: ./frontend
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev
          docker build -t us-central1-docker.pkg.dev/$GOOGLE_PROJECT/${{ env.REPO }}/react-frontend-img:${{ env.TAG }} .
          docker push us-central1-docker.pkg.dev/$GOOGLE_PROJECT/${{ env.REPO }}/react-frontend-img:${{ env.TAG }}

      # - name: deploy to GKE
      #   env:
      #     GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
      #   run: |
      #     gcloud container clusters get-credentials autopilot-cluster-1 --region us-east4
      #     sed -i "s/GOOGLE_PROJECT/$GOOGLE_PROJECT/g" frontend-resources.yaml
      #     sed -i "s/IMAGE_SHA_TAG/${{ env.TAG }}/g" frontend-resources.yaml
      #     sed -i "s/REPO_NAME/${{ env.REPO }}/g" frontend-resources.yaml
      #     kubectl apply -f frontend-resources.yaml

      - name: deploy to cloud run
        id: deploy
        uses: 'google-github-actions/deploy-cloudrun@v2'
        with:
          image: us-central1-docker.pkg.dev/${{ secrets.GOOGLE_PROJECT }}/${{ env.REPO }}/react-frontend-img:${{ env.TAG }}
          service: ${{ env.SERVICE }}
          region: ${{ env.REGION }}

      # If required, use the Cloud Run url output in later steps
      - name: show output
        run: echo ${{ steps.deploy.outputs.url }}